import { useCallback } from 'react';
import { useI18n } from '@/lib/i18n';

const messages = {
  dashboard: ['Dashboard', 'Painel', 'Painel', 'Panel'], studio: ['AI Studio', 'Estúdio IA', 'Estúdio IA', 'Estudio IA'],
  content: ['Content', 'Conteúdo', 'Conteúdo', 'Contenido'], website: ['Website', 'Website', 'Site', 'Sitio web'], system: ['System', 'Sistema', 'Sistema', 'Sistema'],
  modpacks: ['Modpacks', 'Modpacks', 'Modpacks', 'Modpacks'], launchers: ['Launchers', 'Launchers', 'Launchers', 'Launchers'],
  articles: ['Articles', 'Artigos', 'Artigos', 'Artículos'], guides: ['Guides', 'Guias', 'Guias', 'Guías'], faq: ['FAQ', 'FAQ', 'FAQ', 'Preguntas'], releases: ['Releases', 'Versões', 'Versões', 'Versiones'],
  media: ['Media', 'Multimédia', 'Média', 'Multimedia'], locales: ['Translations', 'Traduções', 'Traduções', 'Traducciones'], homepage: ['Homepage', 'Página inicial', 'Página inicial', 'Inicio'], settings: ['Settings', 'Definições', 'Configurações', 'Ajustes'],
  drafts: ['Drafts', 'Rascunhos', 'Rascunhos', 'Borradores'], deployments: ['Deployments', 'Deploys', 'Implantações', 'Despliegues'], activity: ['Activity', 'Atividade', 'Atividade', 'Actividad'], legacy: ['Historical content', 'Conteúdo histórico', 'Conteúdo histórico', 'Contenido histórico'],
  search: ['Search content, guides, modpacks…', 'Pesquisar conteúdo, guias, modpacks…', 'Buscar conteúdo, guias, modpacks…', 'Buscar contenido, guías y modpacks…'],
  searchItems: ['Search this collection', 'Pesquisar esta coleção', 'Buscar nesta coleção', 'Buscar en esta colección'],
  open: ['Open', 'Abrir', 'Abrir', 'Abrir'], edit: ['Edit', 'Editar', 'Editar', 'Editar'], new: ['New private draft', 'Novo rascunho privado', 'Novo rascunho privado', 'Nuevo borrador privado'],
  overview: ['Content overview', 'Visão geral do conteúdo', 'Visão geral do conteúdo', 'Resumen de contenido'],
  published: ['Published in Git', 'Publicado no Git', 'Publicado no Git', 'Publicado en Git'], draft: ['Private draft', 'Rascunho privado', 'Rascunho privado', 'Borrador privado'],
  missing: ['Missing', 'Em falta', 'Ausente', 'Faltante'], partial: ['Partial', 'Parcial', 'Parcial', 'Parcial'], complete: ['Complete', 'Completo', 'Completo', 'Completo'],
  original: ['Original', 'Original', 'Original', 'Original'], fallback: ['Original shown', 'Original apresentado', 'Original exibido', 'Se muestra original'], review: ['Needs review', 'Precisa de revisão', 'Precisa de revisão', 'Requiere revisión'],
  locale: ['Language', 'Idioma', 'Idioma', 'Idioma'], filter: ['Filter by status', 'Filtrar por estado', 'Filtrar por status', 'Filtrar por estado'], all: ['All', 'Todos', 'Todos', 'Todos'],
  status: ['Status', 'Estado', 'Status', 'Estado'], unknown: ['Unknown', 'Desconhecido', 'Desconhecido', 'Desconocido'], configured: ['Configured', 'Configurado', 'Configurado', 'Configurado'], unavailable: ['Unavailable', 'Indisponível', 'Indisponível', 'No disponible'],
  connected: ['Connected', 'Ligado', 'Conectado', 'Conectado'], preview: ['Preview', 'Pré-visualizar', 'Pré-visualizar', 'Vista previa'],
  siteStatus: ['Site status', 'Estado do site', 'Status do site', 'Estado del sitio'], cmsStatus: ['CMS session', 'Sessão CMS', 'Sessão CMS', 'Sesión CMS'], github: ['GitHub access', 'Acesso GitHub', 'Acesso GitHub', 'Acceso GitHub'], modrinth: ['Modrinth', 'Modrinth', 'Modrinth', 'Modrinth'],
  lastDeploy: ['Last deployment', 'Último deploy', 'Última implantação', 'Último despliegue'], quick: ['Quick create / edit', 'Criar / editar rapidamente', 'Criar / editar rapidamente', 'Crear / editar rápidamente'],
  workflow: ['Publishing workflow', 'Fluxo de publicação', 'Fluxo de publicação', 'Flujo de publicación'],
  livePreview: ['Site preview', 'Pré-visualização do site', 'Pré-visualização do site', 'Vista previa del sitio'],
  activityEmpty: ['No activity feed is connected yet.', 'Ainda não há histórico de atividade ligado.', 'Ainda não há histórico de atividades conectado.', 'Aún no hay historial de actividad conectado.'],
  previewUnavailable: ['Preview origin has not been verified.', 'A origem do Preview ainda não foi verificada.', 'A origem do Preview ainda não foi verificada.', 'Aún no se ha verificado el origen del Preview.'],
  translations: ['Translation progress', 'Progresso das traduções', 'Progresso das traduções', 'Progreso de traducción'],
  requiresAttention: ['Needs attention', 'Precisa de atenção', 'Precisa de atenção', 'Requiere atención'],
  counts: ['Published entries', 'Entradas publicadas', 'Entradas publicadas', 'Entradas publicadas'],
  signout: ['Sign out', 'Terminar sessão', 'Sair', 'Cerrar sesión'], visit: ['Visit site', 'Visitar site', 'Visitar site', 'Visitar sitio'],
  retry: ['Retry', 'Tentar novamente', 'Tentar novamente', 'Reintentar'],
  loadError: ['Could not load the CMS. Check the Preview API and retry.', 'Não foi possível carregar o CMS. Verifica a API Preview e tenta novamente.', 'Não foi possível carregar o CMS. Verifique a API Preview e tente novamente.', 'No se pudo cargar el CMS. Comprueba la API Preview e inténtalo de nuevo.'],
  legacyWarning: ['Historical content. Not currently used by the public V2 experience.', 'Conteúdo histórico. Não alimenta atualmente a experiência pública V2.', 'Conteúdo histórico. Atualmente não alimenta a experiência pública V2.', 'Contenido histórico. Actualmente no alimenta la experiencia pública V2.'],
  aiUnavailable: ['No AI provider is connected. No text is generated or published automatically.', 'Não há um fornecedor de IA ligado. Nenhum texto é gerado ou publicado automaticamente.', 'Nenhum provedor de IA está conectado. Nenhum texto é gerado ou publicado automaticamente.', 'No hay proveedor de IA conectado. No se genera ni publica texto automáticamente.'],
  proposal: ['Review a structured proposal', 'Rever uma proposta estruturada', 'Revisar uma proposta estruturada', 'Revisar una propuesta estructurada'],
  proposalHelp: ['Paste a Content V2 JSON item prepared elsewhere. The schema is checked before a private draft can be saved.', 'Cola um item JSON Content V2 preparado externamente. O schema é validado antes de guardar um rascunho privado.', 'Cole um item JSON Content V2 preparado externamente. O schema é validado antes de salvar um rascunho privado.', 'Pega un elemento JSON Content V2 preparado externamente. El esquema se valida antes de guardar un borrador privado.'],
  saveDraft: ['Save private draft', 'Guardar rascunho privado', 'Salvar rascunho privado', 'Guardar borrador privado'],
  publish: ['Publish to Git', 'Publicar no Git', 'Publicar no Git', 'Publicar en Git'],
  discard: ['Discard draft', 'Eliminar rascunho', 'Excluir rascunho', 'Eliminar borrador'],
  selectEntry: ['Select a published entry or private draft.', 'Seleciona uma entrada publicada ou um rascunho privado.', 'Selecione uma entrada publicada ou um rascunho privado.', 'Selecciona una entrada publicada o un borrador privado.'],
  loading: ['Loading content…', 'A carregar conteúdo…', 'Carregando conteúdo…', 'Cargando contenido…'],
  saveNeeded: ['Save the changes as a private draft before publishing.', 'Guarda as alterações como rascunho privado antes de publicar.', 'Salve as alterações como rascunho privado antes de publicar.', 'Guarda los cambios como borrador privado antes de publicar.'],
  noRecords: ['No published entries in this collection.', 'Esta coleção não tem entradas publicadas.', 'Esta coleção não tem entradas publicadas.', 'No hay entradas publicadas en esta colección.'],
  field: ['Field', 'Campo', 'Campo', 'Campo'], before: ['Current', 'Atual', 'Atual', 'Actual'], after: ['Proposed', 'Proposto', 'Proposto', 'Propuesto'],
  validation: ['Invalid proposal. Check the Content V2 schema and slug.', 'Proposta inválida. Verifica o schema Content V2 e o slug.', 'Proposta inválida. Verifique o schema Content V2 e o slug.', 'Propuesta inválida. Revisa el esquema Content V2 y el slug.'],
  draftSaved: ['Private draft saved.', 'Rascunho privado guardado.', 'Rascunho privado salvo.', 'Borrador privado guardado.'],
  releaseInfo: ['A Git commit publishes Content V2; the Preview build must then complete.', 'Um commit Git publica o Content V2; o build Preview deve depois terminar.', 'Um commit Git publica o Content V2; a build Preview deve terminar depois.', 'Un commit Git publica Content V2; después debe terminar la compilación Preview.'],
  source: ['Source language', 'Idioma original', 'Idioma original', 'Idioma original'],
  ai: ['AI Studio', 'Estúdio IA', 'Estúdio IA', 'Estudio IA'], navigation: ['Navigation', 'Navegação', 'Navegação', 'Navegación'], seo: ['SEO', 'SEO', 'SEO', 'SEO'],
  previewChanges: ['Review changes', 'Rever alterações', 'Revisar alterações', 'Revisar cambios'],
  collection: ['Collection', 'Coleção', 'Coleção', 'Colección'], slug: ['Slug', 'Slug', 'Slug', 'Slug'],
  proposalInput: ['Proposed item (Content V2 JSON)', 'Item proposto (JSON Content V2)', 'Item proposto (JSON Content V2)', 'Elemento propuesto (JSON Content V2)'],
  proposalReview: ['Validate and compare', 'Validar e comparar', 'Validar e comparar', 'Validar y comparar'],
  noChanges: ['No changes to review.', 'Sem alterações para rever.', 'Sem alterações para revisar.', 'No hay cambios que revisar.'],
  existingDraft: ['Open the existing draft before proposing changes to this slug.', 'Abre o rascunho existente antes de propor alterações a este slug.', 'Abra o rascunho existente antes de propor alterações a este slug.', 'Abre el borrador existente antes de proponer cambios a este slug.'],
  noProvider: ['AI actions await a configured, authenticated provider. You can review a proposal prepared elsewhere.', 'As ações de IA aguardam um fornecedor autenticado. Podes rever uma proposta preparada externamente.', 'As ações de IA aguardam um provedor autenticado. Você pode revisar uma proposta preparada externamente.', 'Las acciones de IA esperan un proveedor autenticado. Puedes revisar una propuesta preparada externamente.'],
  articleAction: ['Generate article', 'Gerar artigo', 'Gerar artigo', 'Generar artículo'], translateAction: ['Translate', 'Traduzir', 'Traduzir', 'Traducir'],
  faqAction: ['Create FAQ', 'Criar FAQ', 'Criar FAQ', 'Crear preguntas'], guideAction: ['Create guide', 'Criar guia', 'Criar guia', 'Crear guía'],
  improveAction: ['Improve copy', 'Melhorar texto', 'Melhorar texto', 'Mejorar texto'], seoAction: ['Suggest SEO', 'Sugerir SEO', 'Sugerir SEO', 'Sugerir SEO'],
  fieldName: ['Name', 'Nome', 'Nome', 'Nombre'], shortDescription: ['Short description', 'Descrição curta', 'Descrição curta', 'Descripción breve'],
  longDescription: ['Long description', 'Descrição longa', 'Descrição longa', 'Descripción larga'],
  unsaved: ['Unsaved changes', 'Alterações não guardadas', 'Alterações não salvas', 'Cambios sin guardar'],
  saved: ['Saved · ready for preview', 'Guardado · pronto para pré-visualização', 'Salvo · pronto para pré-visualização', 'Guardado · listo para vista previa'],
  unsavedDraft: ['New draft', 'Novo rascunho', 'Novo rascunho', 'Nuevo borrador'],
  removeRow: ['Remove row', 'Remover linha', 'Remover linha', 'Quitar fila'], addRow: ['Add row', 'Adicionar linha', 'Adicionar linha', 'Añadir fila'],
  visible: ['Visible', 'Visível', 'Visível', 'Visible'], perLine: ['one per line', 'um por linha', 'um por linha', 'uno por línea'],
  mainTab: ['Main content', 'Conteúdo principal', 'Conteúdo principal', 'Contenido principal'], relationsTab: ['Relations', 'Relações', 'Relações', 'Relaciones'],
  mediaTab: ['Media', 'Multimédia', 'Mídia', 'Multimedia'], localizationTab: ['Translations', 'Traduções', 'Traduções', 'Traducciones'], seoTab: ['SEO', 'SEO', 'SEO', 'SEO'], advancedTab: ['Advanced', 'Avançado', 'Avançado', 'Avanzado'],
  privatePreview: ['Private preview', 'Pré-visualização privada', 'Pré-visualização privada', 'Vista previa privada'], previewLanguage: ['Preview language', 'Idioma da pré-visualização', 'Idioma da pré-visualização', 'Idioma de vista previa'],
  translationState: ['Translation state', 'Estado da tradução', 'Status da tradução', 'Estado de traducción'],
  translationName: ['Translated name', 'Nome traduzido', 'Nome traduzido', 'Nombre traducido'], translationSummary: ['Translated summary', 'Resumo traduzido', 'Resumo traduzido', 'Resumen traducido'],
  translationDescription: ['Translated description', 'Descrição traduzida', 'Descrição traduzida', 'Descripción traducida'], translationBody: ['Translated body', 'Corpo traduzido', 'Corpo traduzido', 'Contenido traducido'],
  translateFields: ['Fields without a translation show the original text. Save only reviewed translations.', 'Os campos sem tradução mostram o texto original. Guarda apenas traduções revistas.', 'Os campos sem tradução exibem o texto original. Salve apenas traduções revisadas.', 'Los campos sin traducción muestran el original. Guarda solo traducciones revisadas.'],
  compare: ['Original / translation', 'Original / tradução', 'Original / tradução', 'Original / traducción'],
  publishedRows: ['Published entries', 'Entradas publicadas', 'Entradas publicadas', 'Entradas publicadas'],
  privateRows: ['Private drafts', 'Rascunhos privados', 'Rascunhos privados', 'Borradores privados'],
  prompt: ['What do you want to change?', 'O que queres alterar?', 'O que você quer alterar?', '¿Qué quieres cambiar?'],
  viewEntry: ['View content', 'Ver conteúdo', 'Ver conteúdo', 'Ver contenido'],
  alreadyPublished: ['Published', 'Publicado', 'Publicado', 'Publicado'],
  overviewCount: ['Items', 'Itens', 'Itens', 'Elementos'],
  previewRequired: ['Preview the saved draft before publishing.', 'Pré-visualiza o rascunho guardado antes de publicar.', 'Pré-visualize o rascunho salvo antes de publicar.', 'Previsualiza el borrador guardado antes de publicar.'],
  reviewBeforePublish: ['Review the translation and set its state to Partial or Complete before publishing.', 'Revê a tradução e define o estado como Parcial ou Completo antes de publicar.', 'Revise a tradução e defina o status como Parcial ou Completo antes de publicar.', 'Revisa la traducción y cambia su estado a Parcial o Completo antes de publicar.'],
  stableId: ['Add a stable ID to this row in Main content to translate it.', 'Adiciona um ID estável à linha no conteúdo principal para a traduzir.', 'Adicione um ID estável à linha no conteúdo principal para traduzir.', 'Añade un ID estable en contenido principal para traducir esta fila.'],
  ownerTitle: ['Owner Control Panel', 'Painel do proprietário', 'Painel do proprietário', 'Panel del propietario'],
  closeMenu: ['Close menu', 'Fechar menu', 'Fechar menu', 'Cerrar menú'], openMenu: ['Open menu', 'Abrir menu', 'Abrir menu', 'Abrir menú'],
  contentVersion: ['Content V2', 'Conteúdo V2', 'Conteúdo V2', 'Contenido V2'],
  checked: ['Restricted', 'Acesso restrito', 'Acesso restrito', 'Acceso restringido'],
  checking: ['Checking CMS session…', 'A verificar sessão CMS…', 'Verificando sessão CMS…', 'Comprobando sesión CMS…'],
  cmsIntro: ['Owner CMS · published content and private drafts', 'CMS do proprietário · conteúdo publicado e rascunhos privados', 'CMS do proprietário · conteúdo publicado e rascunhos privados', 'CMS del propietario · contenido publicado y borradores privados'],
  backToSite: ['Back to site', 'Voltar ao site', 'Voltar ao site', 'Volver al sitio'],
  loginFailure: ['Could not sign in. Check the password and Preview connection.', 'Não foi possível iniciar sessão. Verifica a palavra-passe e a ligação Preview.', 'Não foi possível entrar. Verifique a senha e a conexão Preview.', 'No se pudo iniciar sesión. Comprueba la contraseña y Preview.'],
  loginorigin: ['The CMS Edge Function rejected this origin.', 'A Edge Function do CMS recusou esta origem.', 'A Edge Function do CMS recusou esta origem.', 'La Edge Function del CMS rechazó este origen.'],
  receivedOrigin: ['Origin received', 'Origem recebida', 'Origem recebida', 'Origen recibido'],
  expectedOrigin: ['Preferred Preview alias', 'Alias Preview preferido', 'Endereço Preview preferido', 'Alias Preview preferido'],
  originAllowlistHelp: ['Check that the exact received origin is listed in ADMIN_ORIGINS on Supabase Preview. The preferred alias is a reference, not a login requirement.', 'Confirma que a origem recebida está incluída exatamente em ADMIN_ORIGINS no Supabase Preview. O alias preferido é uma referência, não um requisito de login.', 'Confirme que a origem recebida está incluída exatamente em ADMIN_ORIGINS no Supabase Preview. O endereço preferido é uma referência, não uma exigência de login.', 'Confirma que el origen recibido figure exactamente en ADMIN_ORIGINS de Supabase Preview. El alias preferido es una referencia, no un requisito de inicio de sesión.'],
  logininvalidPassword: ['Incorrect password.', 'Palavra-passe incorreta.', 'Senha incorreta.', 'Contraseña incorrecta.'],
  loginmissingConfig: ['Preview Supabase configuration is missing. Check the Vercel environment and Edge secrets.', 'Falta a configuração Supabase Preview. Verifica o ambiente Vercel e os secrets Edge.', 'Falta a configuração do Supabase Preview. Verifique o ambiente Vercel e os segredos Edge.', 'Falta la configuración de Supabase Preview. Revisa Vercel y los secretos Edge.'],
  loginsessionInvalid: ['Session expired or invalid. Sign in again.', 'Sessão expirada ou inválida. Inicia sessão novamente.', 'Sessão expirada ou inválida. Entre novamente.', 'Sesión caducada o inválida. Inicia sesión de nuevo.'],
  logingithubConfig: ['GitHub token or repository configuration is invalid. Check the Preview Edge secrets.', 'Token GitHub ou configuração do repositório inválidos. Verifica os secrets Edge de Preview.', 'Token GitHub ou configuração do repositório inválidos. Verifique os segredos Edge do Preview.', 'Token GitHub o configuración del repositorio inválidos. Revisa los secretos Edge de Preview.'],
  loginnetwork: ['Could not reach the Preview CMS API. Check network and the Edge CORS allowlist.', 'Não foi possível contactar a API CMS Preview. Verifica a rede e as origens permitidas na Edge.', 'Não foi possível acessar a API CMS Preview. Verifique a rede e as origens permitidas na Edge.', 'No se pudo contactar con la API CMS Preview. Comprueba la red y los orígenes permitidos en Edge.'],
  loginrateLimit: ['Too many attempts. Wait before trying again.', 'Demasiadas tentativas. Espera antes de voltar a tentar.', 'Muitas tentativas. Aguarde antes de tentar novamente.', 'Demasiados intentos. Espera antes de volver a intentarlo.'],
  committedPreview: ['Committed to Preview', 'Commit na branch Preview', 'Commit na branch Preview', 'Commit en la rama Preview'],
  readyLive: ['Preview Ready', 'Preview pronto', 'Preview pronto', 'Preview listo'],
  liveProduction: ['Live / Production (separate release)', 'Live / Production (lançamento separado)', 'Live / Production (lançamento separado)', 'Live / Production (publicación independiente)'],
  awaitingPreview: ['Preview deployment and public content still require verification. No Production deployment is implied.', 'O deployment Preview e o conteúdo público ainda exigem verificação. Isto não indica publicação em Production.', 'A implantação Preview e o conteúdo público ainda exigem verificação. Isto não indica publicação em Production.', 'El despliegue Preview y el contenido público requieren verificación. No indica publicación en Production.'],
  contentReady: ['Published entries use Content V2. Private drafts never appear on the public site.', 'As entradas publicadas usam Content V2. Os rascunhos privados nunca aparecem no site público.', 'As entradas publicadas usam Content V2. Rascunhos privados nunca aparecem no site público.', 'Las entradas publicadas usan Content V2. Los borradores privados nunca aparecen en el sitio público.'],
  branchMismatch: ['Publishing is unavailable until the CMS confirms the Preview repository and branch.', 'A publicação fica indisponível até o CMS confirmar o repositório e a branch Preview.', 'A publicação fica indisponível até o CMS confirmar o repositório e a branch Preview.', 'La publicación no está disponible hasta confirmar el repositorio y la rama Preview.'],
  downloads: ['downloads', 'transferências', 'downloads', 'descargas'], followers: ['followers', 'seguidores', 'seguidores', 'seguidores'],
  moveUp: ['Move up', 'Mover para cima', 'Mover para cima', 'Mover arriba'], moveDown: ['Move down', 'Mover para baixo', 'Mover para baixo', 'Mover abajo'],
  canonical: ['Canonical path', 'Percurso canonical', 'Caminho canonical', 'Ruta canonical'],
  confirmPublish: ['Publish this private draft to the Preview Git branch? The change becomes public after a successful Preview build.', 'Publicar este rascunho na branch Git Preview? A alteração fica pública após o build Preview terminar.', 'Publicar este rascunho na branch Git Preview? A alteração fica pública após a build Preview terminar.', '¿Publicar este borrador en la rama Git Preview? El cambio será público tras completar la compilación Preview.'],
  confirmDelete: ['Permanently delete this private draft?', 'Eliminar definitivamente este rascunho privado?', 'Excluir permanentemente este rascunho privado?', '¿Eliminar definitivamente este borrador privado?'],
  draftExists: ['A private draft already exists for this slug. Open it first.', 'Já existe um rascunho privado para este slug. Abre-o primeiro.', 'Já existe um rascunho privado para este slug. Abra-o primeiro.', 'Ya existe un borrador privado para este slug. Ábrelo primero.'],
  saveFailed: ['Check the fields and retry saving the private draft.', 'Verifica os campos e tenta guardar o rascunho privado.', 'Verifique os campos e tente salvar o rascunho privado.', 'Revisa los campos e intenta guardar el borrador privado.'],
  publishFailed: ['Publishing failed. The draft remains private; check the revision and Git branch.', 'A publicação falhou. O rascunho continua privado; verifica a revisão e a branch Git.', 'A publicação falhou. O rascunho continua privado; verifique a revisão e a branch Git.', 'La publicación falló. El borrador sigue privado; comprueba la revisión y la rama Git.'],
  deleteFailed: ['Could not delete the private draft. Retry.', 'Não foi possível eliminar o rascunho privado. Tenta novamente.', 'Não foi possível excluir o rascunho privado. Tente novamente.', 'No se pudo eliminar el borrador privado. Reintenta.'],
  translateWithAi: ['Translate with AI', 'Traduzir com IA', 'Traduzir com IA', 'Traducir con IA'],
} as const;

type Key = keyof typeof messages;
const index = { en: 0, 'pt-PT': 1, 'pt-BR': 2, es: 3 } as const;
export const adminText = (locale: keyof typeof index, key: Key): string => messages[key][index[locale]];
export function useAdminText() { const { locale } = useI18n(); return useCallback((key: Key) => adminText(locale, key), [locale]); }
