import type { Locale } from '@/content';

// Human-facing labels for schema fields; stored values remain locale-neutral.
const labels: Record<string, [string, string, string]> = {
  'Project status (independent of version)': ['Estado do projeto (independente da versão)', 'Status do projeto (independente da versão)', 'Estado del proyecto (independiente de la versión)'],
  'Release slugs': ['Slugs das versões', 'Slugs das versões', 'Slugs de versiones'],
  'Installation': ['Instalação', 'Instalação', 'Instalación'], 'Recommendations': ['Recomendações', 'Recomendações', 'Recomendaciones'],
  'Known issues': ['Problemas conhecidos', 'Problemas conhecidos', 'Problemas conocidos'], 'Compatibility': ['Compatibilidade', 'Compatibilidade', 'Compatibilidad'],
  'Compatibility: minecraft': ['Versões Minecraft', 'Versões Minecraft', 'Versiones Minecraft'],
  'Compatibility: loaders': ['Carregadores', 'Carregadores', 'Cargadores'],
  'Compatibility: platforms': ['Plataformas', 'Plataformas', 'Plataformas'],
  'Environment (optional)': ['Ambiente (opcional)', 'Ambiente (opcional)', 'Entorno (opcional)'],
  'Environment': ['Ambiente', 'Ambiente', 'Entorno'],
  'Distribution providers': ['Fontes de distribuição', 'Fontes de distribuição', 'Proveedores de distribución'],
  'Features': ['Funcionalidades', 'Recursos', 'Características'], 'Requirements': ['Requisitos', 'Requisitos', 'Requisitos'],
  'Benchmarks (with method/source)': ['Benchmarks (método/fonte)', 'Benchmarks (método/fonte)', 'Pruebas de rendimiento (método/fuente)'],
  'Roadmap': ['Roteiro', 'Roteiro', 'Plan futuro'], 'Project slug': ['Slug do projeto', 'Slug do projeto', 'Slug del proyecto'],
  'Project slug (optional)': ['Slug do projeto (opcional)', 'Slug do projeto (opcional)', 'Slug del proyecto (opcional)'],
  'Version': ['Versão', 'Versão', 'Versión'], 'Release channel': ['Canal da versão', 'Canal da versão', 'Canal de versión'],
  'Release date (ISO 8601; optional)': ['Data da versão (ISO 8601; opcional)', 'Data da versão (ISO 8601; opcional)', 'Fecha de versión (ISO 8601; opcional)'],
  'Release compatibility (optional; takes priority over project defaults)': ['Compatibilidade da versão (opcional; prioritária)', 'Compatibilidade da versão (opcional; prioritária)', 'Compatibilidad de versión (opcional; prioritaria)'],
  'Changelog': ['Alterações da versão', 'Alterações da versão', 'Cambios de versión'], 'Platforms': ['Plataformas', 'Plataformas', 'Plataformas'],
  'Ease of use': ['Facilidade de utilização', 'Facilidade de uso', 'Facilidad de uso'],
  'Pros': ['Vantagens', 'Vantagens', 'Ventajas'], 'Cons': ['Desvantagens', 'Desvantagens', 'Desventajas'],
  'Official links': ['Links oficiais', 'Links oficiais', 'Enlaces oficiales'],
  'Body (Markdown)': ['Corpo (Markdown)', 'Corpo (Markdown)', 'Contenido (Markdown)'],
  'Category': ['Categoria', 'Categoria', 'Categoría'], 'Author': ['Autor', 'Autor', 'Autor'],
  'Published date (ISO 8601; optional)': ['Data de publicação (ISO 8601; opcional)', 'Data de publicação (ISO 8601; opcional)', 'Fecha de publicación (ISO 8601; opcional)'],
  'Launcher slug (optional)': ['Slug do launcher (opcional)', 'Slug do launcher (opcional)', 'Slug del launcher (opcional)'],
  'Updated date (ISO 8601; optional)': ['Data de atualização (ISO 8601; opcional)', 'Data de atualização (ISO 8601; opcional)', 'Fecha de actualización (ISO 8601; opcional)'],
  'Level': ['Nível', 'Nível', 'Nivel'], 'Steps': ['Passos', 'Etapas', 'Pasos'],
  'Questions (optional stable id for deep links)': ['Perguntas (ID estável opcional para links)', 'Perguntas (ID estável opcional para links)', 'Preguntas (ID estable opcional para enlaces)'],
  'Hero eyebrow': ['Rótulo do hero', 'Rótulo do hero', 'Etiqueta del hero'], 'Hero title': ['Título do hero', 'Título do hero', 'Título del hero'],
  'Hero subtitle': ['Subtítulo do hero', 'Subtítulo do hero', 'Subtítulo del hero'],
  'Hero primary project slug': ['Slug do projeto principal', 'Slug do projeto principal', 'Slug del proyecto principal'],
  'Featured project slugs (ordered)': ['Slugs de projetos destacados (por ordem)', 'Slugs de projetos destacados (em ordem)', 'Slugs de proyectos destacados (en orden)'],
  'Featured article slugs (ordered)': ['Slugs de artigos destacados (por ordem)', 'Slugs de artigos destacados (em ordem)', 'Slugs de artículos destacados (en orden)'],
  'Notices': ['Avisos', 'Avisos', 'Avisos'], 'Contact email': ['Email de contacto', 'Email de contato', 'Correo de contacto'],
  'Sections': ['Secções', 'Seções', 'Secciones'], 'Quick links': ['Links rápidos', 'Links rápidos', 'Enlaces rápidos'],
  'Support intro': ['Introdução ao suporte', 'Introdução ao suporte', 'Introducción al soporte'],
  'Community intro': ['Introdução à comunidade', 'Introdução à comunidade', 'Introducción a la comunidad'],
  'Navigation': ['Navegação', 'Navegação', 'Navegación'], 'Footer': ['Rodapé', 'Rodapé', 'Pie de página'],
  'Project FAQ': ['FAQ do projeto', 'FAQ do projeto', 'Preguntas del proyecto'],
  'Meta title': ['Título SEO', 'Título SEO', 'Título SEO'], 'Meta description': ['Descrição SEO', 'Descrição SEO', 'Descripción SEO'],
  'Social image URL': ['URL da imagem social', 'URL da imagem social', 'URL de imagen social'],
  'SEO title': ['Título SEO', 'Título SEO', 'Título SEO'], 'SEO description': ['Descrição SEO', 'Descrição SEO', 'Descripción SEO'],
  id: ['ID estável', 'ID estável', 'ID estable'], title: ['Título', 'Título', 'Título'], description: ['Descrição', 'Descrição', 'Descripción'],
  body: ['Corpo', 'Corpo', 'Contenido'], question: ['Pergunta', 'Pergunta', 'Pregunta'], answer: ['Resposta', 'Resposta', 'Respuesta'],
  label: ['Rótulo', 'Rótulo', 'Etiqueta'], value: ['Valor', 'Valor', 'Valor'], source: ['Fonte', 'Fonte', 'Fuente'],
  provider: ['Fonte', 'Fonte', 'Proveedor'], state: ['Estado', 'Status', 'Estado'], priority: ['Prioridade', 'Prioridade', 'Prioridad'],
  note: ['Nota', 'Nota', 'Nota'], icon: ['Ícone', 'Ícone', 'Icono'], methodology: ['Método', 'Método', 'Método'],
  unit: ['Unidade', 'Unidade', 'Unidad'], url: ['URL', 'URL', 'URL'], alt: ['Texto alternativo', 'Texto alternativo', 'Texto alternativo'],
  caption: ['Legenda', 'Legenda', 'Leyenda'], kind: ['Tipo', 'Tipo', 'Tipo'], text: ['Texto', 'Texto', 'Texto'],
  link: ['Link', 'Link', 'Enlace'], path: ['Percurso', 'Caminho', 'Ruta'],
  intro: ['Introdução', 'Introdução', 'Introducción'], ctaLabel: ['Rótulo da ação', 'Rótulo da ação', 'Texto de la acción'],
  active: ['Ativo', 'Ativo', 'Activo'], paused: ['Pausado', 'Pausado', 'Pausado'], outdated: ['Desatualizado', 'Desatualizado', 'Desactualizado'],
  primary: ['Principal', 'Principal', 'Principal'], secondary: ['Secundário', 'Secundário', 'Secundario'],
  beginner: ['Iniciante', 'Iniciante', 'Principiante'], intermediate: ['Intermédio', 'Intermediário', 'Intermedio'], advanced: ['Avançado', 'Avançado', 'Avanzado'],
  development: ['Em desenvolvimento', 'Em desenvolvimento', 'En desarrollo'], 'internal-prototype': ['Protótipo interno', 'Protótipo interno', 'Prototipo interno'],
  archived: ['Arquivado', 'Arquivado', 'Archivado'], stable: ['Estável', 'Estável', 'Estable'],
  unspecified: ['Não especificado', 'Não especificado', 'Sin especificar'], client: ['Cliente', 'Cliente', 'Cliente'], server: ['Servidor', 'Servidor', 'Servidor'], both: ['Ambos', 'Ambos', 'Ambos'],
  planned: ['Planeado', 'Planejado', 'Planificado'], 'in-progress': ['Em curso', 'Em andamento', 'En curso'], done: ['Concluído', 'Concluído', 'Completado'],
  'needs-review': ['Precisa de revisão', 'Precisa de revisão', 'Requiere revisión'], partial: ['Parcial', 'Parcial', 'Parcial'], complete: ['Completo', 'Completo', 'Completo'],
};

export function editorLabel(locale: Locale, label: string): string {
  const idx = locale === 'pt-PT' ? 0 : locale === 'pt-BR' ? 1 : locale === 'es' ? 2 : -1;
  return idx === -1 ? label : labels[label]?.[idx] || label;
}
